version: "3.9"
services:
  ranker:
    build: .
    ports:
      - "8080:8080"
    restart: always
    links:
      - mongodb:host.docker.internal
    depends_on:
      - mongodb
    volumes:
      - ./resources:/resources
  mongodb:
    image: mongo:latest
    container_name: mongodb
    network_mode: host
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_container:/data/db

volumes:
  resources:
  mongodb_data_container: